version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    container_name: "db"
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: ''
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

  backend:
    container_name: "backend"
    restart: always
    build:
      context: ''
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:

